version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pedidos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pedidos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pedidos-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pedidos-net

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Porta unificada da AWS
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/etc/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pedidos-net

networks:
  pedidos-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
