openapi: 3.0.4
info:
  title: CreditoParceiro B2B
  version: 1.0.0
  description: >
    API para gerenciar pedidos.

tags:
  - name: CreditoParceiro
    description: Operações relacionadas a credito parceiro

paths:
  /v1/parceiro-credito:
    post:
      summary: Criar um novo parceiro credito
      operationId: criar
      tags:
        - CreditoParceiro
      requestBody:
        description: Criar parceiro credito
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParceiroCreditoRequest'
      responses:
        '201':
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParceiroCreditoResponse'
        '422':
          description: Erro na validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno

components:
  schemas:
    ParceiroCreditoRequest:
      type: object
      required:
        - idParceiro
        - credito
      properties:
        idParceiro:
          type: integer
          format: int64
          example: 1
        credito:
          type: number
          format: double
          example: 1.50
          description: Valor do credito do parceiro

    ParceiroCreditoResponse:
      type: object
      description: Representa a resposta do credito parceiro.
      properties:
        id:
          type: string
          format: uuid
          description: Identificador
          example: 3cb37181-8ea4-4f24-b9a6-02fc16a7d826
        idParceiro:
          type: integer
          format: int64
          example: 1
        credito:
          type: number
          format: double
          example: 1.50
          description: Valor do credito do parceiro

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Erro de validação"
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                example: "campo X é obrigatório"
